apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tb-route-http-transport
  namespace: thingsboard
spec:
  path: /api/v1
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tb-http-transport
  tls:
    termination: Edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tb-route-node
  namespace: thingsboard
spec:
  path: /static/rulenode
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tb-node
  tls:
    termination: Edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tb-route-web-ui
  namespace: thingsboard
spec:
  path: /static
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tb-web-ui
  tls:
    termination: Edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tb-route-web-ui-index
  namespace: thingsboard
spec:
  path: /index.html
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tb-web-ui
  tls:
    termination: Edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tb-route-web-ui-root
  namespace: thingsboard
spec:
  path:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tb-web-ui
  tls:
    termination: Edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tb-route-node-root
  namespace: thingsboard
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tb-node
  tls:
    termination: Edge
---
