apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tb-ingress
  namespace: thingsboard
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/.*
            backend:
              serviceName: tb-http-transport
              servicePort: 8080
          - path: /static/rulenode/.*
            backend:
              serviceName: tb-node
              servicePort: 8080
          - path: /static/.*
            backend:
              serviceName: tb-web-ui
              servicePort: 8080
          - path: /index.html.*
            backend:
              serviceName: tb-web-ui
              servicePort: 8080
          - path: /
            backend:
              serviceName: tb-web-ui
              servicePort: 8080
          - path: /.*
            backend:
              serviceName: tb-node
              servicePort: 8080
---